config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    collection do
      get "top" => "restaurant#top"
    end
    member do
      get "chef" => "restaurant#chef"
    end
    resources :reviews, only: [:new, :create]

    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  CATEGORIES = %w(Chinese Italian Japanese French Belgian)

  validates :category, inclusion: { in: CATEGORIES, allow_nil: false }
  validates :name, presence: true
  validates :address, presence: true
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord

  RATINGS = [1, 2, 3, 4, 5]

  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: RATINGS, allow_nil: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    redirect_to restaurants_path
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :set_restaurant

  def new
    @review = @restaurant.reviews.build
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_path(@restaurant)
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <!-- Add these line for detecting device width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container">
  <h1 class="text-center">Restaurants</h1>
  <p class="text-center"><%= link_to "Add new restaurant", new_restaurant_path %></p>
  <div class="row">
    <% @restaurants.each do |restaurant| %>
    <div class="col-xs-12 col-sm-4 text-center card">
      <div class="card" style="background: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('app/assets/images/resto.png');">
        <h3><%= restaurant.name %></h3>
        <p><%= restaurant.category.capitalize %></p>
        <p><%= restaurant.address %></p>
        <p><%= restaurant.phone_number %></p>
        <%= link_to "More details", restaurant_path(restaurant) %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<h1 class="text-center" >Add new restaurant</h1>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= simple_form_for @restaurant do |f| %>
      <%= f.input :name, placeholder: "Brindisa" %>
      <%= f.input :address, placeholder: "10 Downing Street" %>
      <%= f.input :category, collection: Restaurant::CATEGORIES, prompt: "Choose one"  %>
      <%= f.input :phone_number, placeholder: "07 123 45 6789" %>
      <%= f.submit "submit", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h1><%= @restaurant.name %></h1>
  <p><%= @restaurant.category.capitalize %></p>
  <p><%= @restaurant.address %></p>
  <p><%= @restaurant.phone_number %></p>

  <ul>
    <% @restaurant.reviews.each do |review| %>
      <li><%= review.content %> (<%= review.rating %>)</li>
    <% end %>
  </ul>

  <%= link_to "Back to all restaurants", restaurants_path %>
  </br>
  <%= link_to "Add a review", new_restaurant_review_path(@restaurant.id) %>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h4>Add a review for <%= @restaurant.name %></h4>
      <%= simple_form_for [@restaurant, @review] do |f| %>
      <%= f.input :content, placeholder: "Amazing!" %>
       <%= f.input :rating, collection: Review::RATINGS, prompt: "1 to 5" %>
      <%= f.submit "submit", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<p class="text-center padded">This is a footer</p>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to "app/assets/images", class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Notification -->
    <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
      <div class="badge-container">
        <i class="fa fa-envelope-o"></i>
        <div class="badge badge-blue">3</div>
      </div>
    <% end %>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>